### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by neverdry** [Flyingblu/Mediasite-Utility-for-XMUM#1]
1. 服务器显示没有权限下载
2. 无法复制视频链接

**Comment by Flyingblu** [comment]
复制链接的问题可能跟chrome版本有关，可以尝试把chrome升至最新。我之后会想办法解决这个问题😂

**Comment by Flyingblu** [comment]
没有权限是下载链接中的playbackticket失效导致的，建议重新获取链接下载。

**Comment by Flyingblu** [comment]
显示链接界面已更新 issue关闭
