### ISSUE TITLE
求添加其他大学mediasite的支持

### ISSUE THREAD

**Issue by dzhang121** [Flyingblu/Mediasite-Utility-for-XMUM#3]
域名是mediasite.bris.ac.uk
例如https://mediasite.bris.ac.uk/Mediasite/Play/58bfab74485248c086b088b1df6bc1551d?catalog=4db3e50cb7ab42e9bcb48a4d627c2a8521

感谢

**Comment by Flyingblu** [comment]
我不太清楚你们大学的认证方式，也没法登录去测试，所以可能添加支持会比较困难。
你需要哪方面的功能？或许你可以使用我找到的API来实现。

**Comment by Flyingblu** [comment]
Close issue due to inactivity.
